# -*- coding: utf-8 -*-
"""data analysis task 1 web scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ToOQJvbEQleLfhNVCyJfIVgdGHl2fuI

# umarfarooq
# student id;  CA/DF1/86355
# data analysis
# CodeAlpha Internship Task 1: Web Scraping
#  Tool: BeautifulSoup + requests
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

BASE_URL = "http://books.toscrape.com/catalogue/"

def get_star_rating(tag):
    """Convert word-based star rating to a number."""
    word_to_num = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
    rating_word = tag["class"][1]          # e.g. 'Three'
    return word_to_num.get(rating_word, 0)

def scrape_page(url):
    """Scrape all books from a single catalogue page."""
    response = requests.get(url, timeout=10)
    soup = BeautifulSoup(response.text, "html.parser")

    books = []
    for article in soup.select("article.product_pod"):
        title  = article.h3.a["title"]
        price  = article.select_one(".price_color").text.strip()
        rating = get_star_rating(article.select_one(".star-rating"))
        avail  = article.select_one(".availability").text.strip()

        cleaned_price = price.replace("£", "").replace("Â", "")

        books.append({
            "title":        title,
            "price_gbp":    float(cleaned_price),
            "star_rating":  rating,
            "availability": avail,
        })
    return books, soup

def get_next_page(soup, current_url):
    """Return the URL of the next page, or None if we're on the last page."""
    next_btn = soup.select_one("li.next > a")
    if not next_btn:
        return None
    folder   = current_url.rsplit("/", 1)[0] + "/"
    return folder + next_btn["href"]

def scrape_all_books(max_pages=5):
    """
    Scrape up to max_pages pages of books.
    books.toscrape.com has 50 pages total — we keep it short by default.
    """
    url      = BASE_URL + "page-1.html"
    all_books = []
    page_num  = 1

    print(f"Starting scrape — collecting up to {max_pages} pages...\n")

    while url and page_num <= max_pages:
        print(f"  Scraping page {page_num}: {url}")
        books, soup = scrape_page(url)
        all_books.extend(books)
        url = get_next_page(soup, url)
        page_num += 1
        time.sleep(0.5)

    return all_books

def main():
    books     = scrape_all_books(max_pages=5)
    df        = pd.DataFrame(books)

    print(f"\n✅ Scraped {len(df)} books total.")
    print("\nTop 10 highest-rated & cheapest books:")
    top = (df[df["star_rating"] == 5]
             .sort_values("price_gbp")
             .head(10)[["title", "price_gbp", "star_rating"]])
    print(top.to_string(index=False))

    df.to_csv("scraped_books.csv", index=False)
    print("\n Data saved to scraped_books.csv")

if __name__ == "__main__":
    main()